# .github/workflows/deploy.yml
name: Deploy to ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy Docker App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker image
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/health-agent:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy Terraform
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve
