name: Deploy Docker to ECS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag, and Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/health-agent:latest
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Register new ECS Task Definition revision
        run: |
          TASK_DEF=$(aws ecs describe-task-definition --task-definition agent-task)
          IMAGE_URI="${{ env.IMAGE_URI }}"
          TASK_ROLE_ARN="arn:aws:iam::443370680070:role/ecsTaskAppRole"

          NEW_TASK_DEF=$(echo "$TASK_DEF" | jq --arg IMAGE "$IMAGE_URI" --arg TASK_ROLE_ARN "$TASK_ROLE_ARN" '
            .taskDefinition |
            {
              family,
              networkMode,
              containerDefinitions,
              requiresCompatibilities,
              cpu,
              memory,
              executionRoleArn,
              taskRoleArn: $TASK_ROLE_ARN
            } |
            (.containerDefinitions[0].image = $IMAGE) |
            {
              family,
              networkMode,
              containerDefinitions,
              requiresCompatibilities,
              cpu,
              memory,
              executionRoleArn,
              taskRoleArn
            }')

          echo "$NEW_TASK_DEF" > new-task-def.json
          aws ecs register-task-definition --cli-input-json file://new-task-def.json

      - name: Update ECS Service to use new Task Definition
        run: |
          NEW_TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition agent-task \
            --query 'taskDefinition.taskDefinitionArn' --output text)

          aws ecs update-service \
            --cluster agent-cluster \
            --service agent-service \
            --task-definition $NEW_TASK_DEF_ARN

      - name: Wait for ECS service to stabilize
        run: sleep 600

      - name: Trigger k6-test.yml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/k6-test.yml/dispatches \
            -d '{"ref":"main"}'
